---
title             : "Automatically Extracting ERP Component Latencies Using a Dynamic Template Matching Algorithm"
shorttitle        : "Template Matching"

author: 
  - name          : "Sven Lesche"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Im Neuenheimer Feld 695, 69120 Heidelberg"
    email         : "sven.lesche@psychologie.uni-heidelberg.de"
    # role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
    #   - "Conceptualization"
    #   - "Writing - Original Draft Preparation"
    #   - "Writing - Review & Editing"
  # - name          : "Author 2"
  #   affiliation   : "2"
  #   role:
  #     - "Supervision"

affiliation:
  - id            : "1"
    institution   : "Ruprecht-Karls-University Heidelberg"
  # - id            : "2"
  #   institution   : "Konstanz Business School"
  # add a second id using this syntax

authornote: |
  This work represents the author’s master-thesis. It was completed in R-Markdown with the code for data preparation, analysis and communication integrated into the scripts. All code needed to replicate this work can be found at: https://github.com/SLesche/master.

abstract: |
  Extraction of the latency of event-related potentials (ERPs) of the EEG allows insight into the timing of cognitive processes.
  This work introduces a novel algorithm for latency extraction based on detecting a component using a template. The algorithm uses the grand average to generate an experiment-specific template of the component of interest and then matches transformations of that template to subject-level ERPs. These transformations allow quantification of individual differences in latency.
  I compared the new algorithm to peak latency and area latency algorithms by extracting P3 latencies from the same data as Sadus et al. (2023). 
  The new algorithm displayed superior psychometric properties and correlated highly with latency values extracted manually by an expert ERP researcher. The algorithm provides a fit statistic for each subject-level ERP, indicating the degree of certainty it has in its decision. This allows researchers to automatically discard or manually review choices the algorithm has made based on an informative fit statistic.
  While manual review slightly improved the results, the algorithm was able to generate reliable latency values that correlate highly with decisions made manually by an expert even in a fully automatic fashion.
  Application of this template matching algorithm improves psychometric qualities and provides a more objective, efficient, and robust way to extract latencies of ERP components.

keywords          : "event-related potentials, latency extraction, P3, template matching"

bibliography      : ["r-references.bib", "template_matching.bib"] # put your ref files here

floatsintext      : no # for pics in text
linenumbers       : no
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no
link-citations    : true # custom addin, makes citations link to reference section
# figsintext        : yes # custom addin

classoption       : "man"
# the settings below allow compilation of APA7 style citations/documents
header-includes:
  - |
    \makeatletter
    \renewcommand{\paragraph}{\@startsection{paragraph}{4}{\parindent}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-1em}%
      {\normalfont\normalsize\bfseries\typesectitle}}
    
    \renewcommand{\subparagraph}[1]{\@startsection{subparagraph}{5}{1em}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-\z@\relax}%
      {\normalfont\normalsize\bfseries\itshape\hspace{\parindent}{#1}\textit{\addperi}}{\relax}}
    \makeatother
  - | 
    \raggedbottom
  - |
    \usepackage{hhline}
  - |
    \setlength{\parskip}{0pt}
  - |
    % This is for using the flextable package
    \usepackage{colortbl}
    % Flextable just forgets these two
    \newlength{\Oldarrayrulewidth}
    \newlength{\Oldtabcolsep}
    % This one is placed inside a table environment, so need to call it earlier
    \providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}
csl               : "`r system.file('rmd', 'apa7.csl', package = 'papaja')`"
documentclass     : "apa7"
output            : papaja::apa6_pdf
---
```{r setup, include = FALSE}
# Working directory
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

# disallow tables breaking over pages
knitr::opts_chunk$set(ft.keepnext = TRUE,
                      ft.align = "left",
                      ft.latex.float = "float")
# Seed for random number generation
set.seed(1234)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed) # this adds random seed to all chunks
knitr::opts_chunk$set(autodep = TRUE)
knitr::dep_auto()

# disable all in-document warnings
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
```

<!-- Setup -->
```{r child = "markdown/setup.Rmd"}
```
<!-- Here we incorporate child markdown-documents as the separate parts -->

<!-- Introduction -->
```{r child = "markdown/introduction.Rmd"}
```

<!-- Method -->
```{r child = "markdown/method.Rmd"}
```

<!-- Results -->
```{r child = "markdown/results.Rmd"}
```

<!-- Discussion -->
```{r child = "markdown/discussion.Rmd"}
```

<!-- References -->
\newpage
# References
::: {#refs custom-style="Bibliography"}
:::

<!-- \newpage -->

<!-- # (APPENDIX) Appendix {-} -->

<!-- ```{r child = "markdown/appendix.Rmd"} -->
<!-- ``` -->


