# Results
```{r}
source("markdown/analysis/estimate_reliability_results.R")
```

All data wrangling and statistical analyses were conducted in R [Version, Citation]. We used the packages [packages]. 

## Review process
We reviewed results of the CORR and MINSQ algorithms if their fit was below $r_{st} \le .60$. **make by MINSQ, CORR** Out of [NUMBER] ERPs evaluated by the algorithms, we inspected [PERCENT of CORR] of ERPs, rejected [PERCENT] of ERPs and accepted [PERCENT] of the results despite their fit. We manually corrected the decisions in [PERCENT] of cases. When reporting the psychometric properties of the algorithms, we will focus on those values passed through manual inspection with those passed through the automatic rejection filter reported in parenthesis.

## Reliability
An overview of Spearman-Brown corrected split-half correlations $r_{tt}$ split by task, measurement window and filter setting can be found in [TABLE]. Across tasks, measurement windows and filter settings the CORR algorithm **that we manually reviewed** had mean split-half correlations of $\bar{r_{tt}} =$ `r mean_reliability_overall %>% filter(approach == "corr", review == "manual") %>% pull(mean) %>% apa_num(gt1 = FALSE)` ($\bar{r_{tt}} =$ `r mean_reliability_overall %>% filter(approach == "corr", review == "auto") %>% pull(mean) %>% apa_num(gt1 = FALSE)`), the MINSQ algorithm $\bar{r_{tt}} =$ `r mean_reliability_overall %>% filter(approach == "minsq", review == "manual") %>% pull(mean) %>% apa_num(gt1 = FALSE)` ($\bar{r_{tt}} =$ `r mean_reliability_overall %>% filter(approach == "minsq", review == "auto") %>% pull(mean) %>% apa_num(gt1 = FALSE)`). Uninformed area latency measures presented even better mean split-correlations $\bar{r_{tt}} =$ `r mean_reliability_overall %>% filter(approach == "uninformed", type == "autoarea", review == "none") %>% pull(mean) %>% apa_num(gt1 = FALSE)`. The average split-half correlation for values extracted by an expert ERP researcher was $\bar{r_{tt}} = .92$ for area latency measures and $\bar{r_{tt}} = .93$ for peak latency measures [Sadus 2023].
<!-- Here, I looked at the table 3 in Sadus et al. 2023, averaging values for 8Hz, 16Hz and 32Hz condition -->

## Homogeneity
An overview of a method's mean correlation with other methods $r_h$ split by task, measurement window and filter setting can be found in [TABLE]. Across tasks, measurement windows and filter settings the CORR algorithm **that we manually reviewed** had a homogeneity of $\bar{r_{h}} =$ `r mean_homogeneity_overall %>% filter(method1_approach == "corr", method1_review == "manual") %>% pull(mean) %>% apa_num(gt1 = FALSE)` ($\bar{r_{h}} =$ `r mean_homogeneity_overall %>% filter(method1_approach == "corr", method1_review == "auto") %>% pull(mean) %>% apa_num(gt1 = FALSE)`), the MINSQ algorithm $\bar{r_{h}} =$ `r mean_homogeneity_overall %>% filter(method1_approach == "minsq", method1_review == "manual") %>% pull(mean) %>% apa_num(gt1 = FALSE)` ($\bar{r_{h}} =$ `r mean_homogeneity_overall %>% filter(method1_approach == "minsq", method1_review == "auto") %>% pull(mean) %>% apa_num(gt1 = FALSE)`). Uninformed area latency measures presented worse homogeneities. $\bar{r_{h}} =$ `r mean_homogeneity_overall %>% filter(method1_approach == "uninformed", method1_type == "autoarea", method1_review == "none") %>% pull(mean) %>% apa_num(gt1 = FALSE)`.

## Effect size
An overview of the effect size of the age effect detect by a particular method split by task, measurement window and filter setting can be found in [TABLE]. Across tasks, measurement windows and filter settings the CORR algorithm **that we manually reviewed** had a mean effect size of $\bar{\omega^2} =$ `r mean_effsize_overall %>% filter(approach == "corr", review == "manual") %>% pull(mean) %>% apa_num(gt1 = FALSE)` ($\bar{\omega^2} =$ `r mean_effsize_overall %>% filter(approach == "corr", review == "auto") %>% pull(mean) %>% apa_num(gt1 = FALSE)`), the MINSQ algorithm $\bar{\omega^2} =$ `r mean_effsize_overall %>% filter(approach == "minsq", review == "manual") %>% pull(mean) %>% apa_num(gt1 = FALSE)` ($\bar{\omega^2} =$ `r mean_effsize_overall %>% filter(approach == "minsq", review == "auto") %>% pull(mean) %>% apa_num(gt1 = FALSE)`). Uninformed area latency measures presented similar average effect sizes $\bar{\omega^2} =$ `r mean_effsize_overall %>% filter(approach == "uninformed", review == "none", type == "autoarea") %>% pull(mean) %>% apa_num(gt1 = FALSE)`. The average effect size for values extracted by an expert ERP researcher [Sadus 2023] was $\bar{\omega^2} = .18$ for area latency measures and $\bar{\omega^2} = .17$ for peak latency measures.
<!-- Here, I looked at the table 3 in Sadus et al. 2023, averaging values for 8Hz, 16Hz and 32Hz condition -->

## Correlation with manual rater
An overview of the correlation with latency values extracted by an expert ERP researcher [Sadus 2023] split by task, measurement window and filter setting can be found in [TABLE]. Across tasks, measurement windows and filter settings the CORR algorithm **that we manually reviewed** had mean correlations of $\bar{r} =$ `r mean_manualcor_overall %>% filter(method2_approach == "corr", method2_review == "manual") %>% pull(mean) %>% apa_num(gt1 = FALSE)` ($\bar{r} =$ `r mean_manualcor_overall %>% filter(method2_approach == "corr", method2_review == "auto") %>% pull(mean) %>% apa_num(gt1 = FALSE)`), the MINSQ algorithm $\bar{r} =$ `r mean_manualcor_overall %>% filter(method2_approach == "minsq", method2_review == "manual") %>% pull(mean) %>% apa_num(gt1 = FALSE)` ($\bar{r} =$ `r mean_manualcor_overall %>% filter(method2_approach == "minsq", method2_review == "auto") %>% pull(mean) %>% apa_num(gt1 = FALSE)`). Uninformed area latency measures had a mean correlation of $\bar{r} =$ `r mean_manualcor_overall %>% filter(method2_approach == "uninformed", method2_review == "none", method2_type == "autoarea") %>% pull(mean) %>% apa_num(gt1 = FALSE)`.

## Influence of researcher degrees of freedom
The repeated measures ANOVA with split-half correlation of a particular method as a dependent variable and the within factors filter (8 Hz vs. 16 Hz vs. 32 Hz) and measurement window (narrow vs. medium vs. wide) showed an effect of filter with [EFFECT] for the CORR algorithm, [EFFECT] for the MINSQ algorithm and [EFFECT] for uninformed area latency measures. The measurement windows had an effect of [EFFECT] for the CORR algorithm, [EFFECT] for the MINSQ algorithm and [EFFECT] for uninformed area latency measures [See TABLE].

When the correlation with manually extracted latencies was used as a dependent variable, the effect of filter settings for the CORR algorithm were [EFFECT], for the MINSQ algorithm [EFFECT] and [EFFECT] for uninformed area latency measures. The measurement windows had an effect of [EFFECT] for the CORR algorithm, [EFFECT] for the MINSQ algorithm and [EFFECT] for uninformed area latency measures [See TABLE].

